#!/usr/bin/env python3
import webbrowser
from threading import Timer

import config
from db import init_db
from web import app, sa

def open_browser():
    if not config.TEST:
        webbrowser.open('http://127.0.0.1:' + str(PORT), new=0, autoraise=True)

if __name__ == "__main__":
    import sys
    if 'TEST' in sys.argv[1:] or 'test' in sys.argv[1:]:
        print("Running in test mode.")
        config.set_test_mode(True)
        print("Checking mode = {}\nApp flags: {}\nSQL_DB: {}"
              .format(config.TEST, config.APP_FLAGS_FILE,
                      config.SQL_DB_PATH))
    print("TEST={}".format(config.TEST))
    init_db(app, sa, force=config.TEST)
    config.setup_logger()
    HOST = "127.0.0.1" if config.DEBUG else "0.0.0.0"
    PORT = 6200 if not (config.TEST or config.DEBUG) else 6202
    Timer(1, open_browser).start()
    app.run(host=HOST, port=PORT, debug=config.DEBUG, use_reloader=(not config.DEBUG))
