"""empty message

Revision ID: 6b4a5c8af161
Revises: 
Create Date: 2019-06-26 15:51:01.088404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b4a5c8af161'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients_notes', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('clients_notes', sa.Column('recorded', sa.Enum('Yes', 'No'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients_notes', 'recorded')
    op.drop_column('clients_notes', 'created_at')
    # ### end Alembic commands ###
