"""empty message

Revision ID: b185ae931b8f
Revises: 
Create Date: 2019-06-27 15:29:43.887656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b185ae931b8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients_notes', sa.Column('caseworker_present', sa.Enum('Yes', 'No'), server_default='', nullable=False))
    op.add_column('clients_notes', sa.Column('caseworker_present_safety_planning', sa.Enum('Yes', 'No'), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients_notes', 'caseworker_present_safety_planning')
    op.drop_column('clients_notes', 'caseworker_present')
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    op.create_table('scan_res',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('clientid', sa.TEXT(), nullable=True),
    sa.Column('serial', sa.TEXT(), nullable=True),
    sa.Column('note', sa.TEXT(), nullable=True),
    sa.Column('device', sa.TEXT(), nullable=True),
    sa.Column('device_model', sa.TEXT(), nullable=True),
    sa.Column('device_manufacturer', sa.TEXT(), nullable=True),
    sa.Column('device_version', sa.TEXT(), nullable=True),
    sa.Column('is_rooted', sa.INTEGER(), nullable=True),
    sa.Column('rooted_reasons', sa.TEXT(), nullable=True),
    sa.Column('last_full_charge', sa.DATETIME(), nullable=True),
    sa.Column('device_primary_user', sa.TEXT(), nullable=True),
    sa.Column('device_access', sa.TEXT(), nullable=True),
    sa.Column('how_obtained', sa.TEXT(), nullable=True),
    sa.Column('time', sa.DATETIME(), server_default=sa.text("datetime('now', 'localtime')"), nullable=True),
    sa.ForeignKeyConstraint(['clientid'], ['clients.clientid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scan_res_clientid', 'scan_res', ['clientid'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('clientid', sa.TEXT(), nullable=True),
    sa.Column('location', sa.TEXT(), nullable=True),
    sa.Column('issues', sa.TEXT(), nullable=True),
    sa.Column('assessment', sa.TEXT(), nullable=True),
    sa.Column('plan', sa.TEXT(), nullable=True),
    sa.Column('the_rest', sa.TEXT(), nullable=True),
    sa.Column('time', sa.DATETIME(), server_default=sa.text("datetime('now', 'localtime')"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_info',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('scanid', sa.INTEGER(), nullable=True),
    sa.Column('appid', sa.TEXT(), nullable=True),
    sa.Column('flags', sa.TEXT(), nullable=True),
    sa.Column('remark', sa.TEXT(), nullable=True),
    sa.Column('action_taken', sa.TEXT(), nullable=True),
    sa.Column('apk_path', sa.TEXT(), nullable=True),
    sa.Column('install_date', sa.DATETIME(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.Column('app_version', sa.TEXT(), nullable=True),
    sa.Column('permissions', sa.TEXT(), nullable=True),
    sa.Column('permissions_reason', sa.TEXT(), nullable=True),
    sa.Column('permissions_used', sa.DATETIME(), nullable=True),
    sa.Column('data_usage', sa.INTEGER(), nullable=True),
    sa.Column('battery_usage', sa.INTEGER(), nullable=True),
    sa.Column('time', sa.DATETIME(), server_default=sa.text("datetime('now', 'localtime')"), nullable=True),
    sa.ForeignKeyConstraint(['scanid'], ['scan_res.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_app_info_scanid', 'app_info', ['scanid'], unique=False)
    # ### end Alembic commands ###
