# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Sync IOC Stalkerware Indicators

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - "scripts/get-stalkerware-indicators.py"
      - ".github/workflows/get-stalkerware-indicators.yml"
      - "requirements.txt"
  schedule:
    # Weekly on Sunday at 00:00 UTC
    - cron: '0 0 * * 0'

permissions:
  contents: write
  pull-requests: write

jobs:
  update-indicators:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml

    - name: Update
      run: |
        python scripts/get-stalkerware-indicators.py

    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v5
      with:
        add-paths: |
          src/isdi/data/app-flags.csv

        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update stalkerware indicators
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: chore/update-stalkerware-indicators
        delete-branch: true
        title: 'Update stalkerware indicators'
        body: |
          Update stalkerware indicators.
          - Updated with *today's* date
          - Auto-generated by [create-pull-request][1]

          [1]: https://github.com/peter-evans/create-pull-request
        labels: |
          report
          automated pr
        assignees: rchatterjee
        reviewers: rchatterjee, naman
        draft: false
    - name: Check outputs
      if: ${{ steps.cpr.outputs.pull-request-number }}
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
